Feature/criar conta endpoint
denisdev-cepedi/Cepedi.Banco.Conta pull request #9
Opened 2024-04-23 02:50 UTC by DStalkerBR

2024-04-23 22:35 UTC, denisdev-cepedi requested changes

2024-04-23 22:35 UTC, denisdev-cepedi commented on src/Cepedi.Banco.Conta.Dominio/Handlers/CriarContaRequestHandler.cs
> +        {
Remover o try catch, não há necessidade uma vez que temos o pipeline de exceção.

2024-04-23 22:35 UTC, denisdev-cepedi commented on src/Cepedi.Banco.Conta.Dominio/Handlers/CriarContaRequestHandler.cs
> +        {
Remover o try catch, não há necessidade uma vez que temos o pipeline de exceção.

2024-04-23 23:30 UTC, DStalkerBR commented on src/Cepedi.Banco.Conta.Dominio/Handlers/CriarContaRequestHandler.cs
> +        {
Try catch foi removido

2024-04-24 17:35 UTC, denisdev-cepedi approved these changes

2024-04-24 17:35 UTC, merged